default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
<<<<<<< HEAD
  database: myapp_development
=======
  database: server_development
  #username: postgres
  #password: 5656
  #localhost: ''
>>>>>>> butt


test:
  <<: *default
  database: myapp_test
